# Generated by Django 4.0.1 on 2022-12-23 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Пользователь Tg', 'verbose_name_plural': 'Пользователи Tg'},
        ),
        migrations.AddField(
            model_name='tguser',
            name='tg_username',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Пользователь'),
        ),
    ]
