# Generated by Django 4.0.1 on 2023-01-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=76, null=True, unique=True, verbose_name='Код верификации'),
        ),
    ]
