# Generated by Django 4.0.1 on 2022-12-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_tguser_options_tguser_tg_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Пользователь Tlgrm', 'verbose_name_plural': 'Пользователи Tlgrm'},
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='tg_username',
        ),
        migrations.AlterField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Код верификации'),
        ),
    ]
